config/routes.rb
Synergy::Application.routes.draw do
  devise_for :users

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply, :restore, :mark_as_read
    end

    collection do 
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  root :to => 'conversations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  #mailboxer
  acts_as_messageable

  def mailboxer_email(object)
    #return the model's email here
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :configure_permitted_parameters, if: :devise_controller?

  #rescue - apparently, this works!
  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end
   
  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name)}
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name)}
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	#these happen at the beginning of the controller call!
	before_filter :authenticate_user!
	before_filter :get_mailbox
	before_filter :get_conversation, except: [:index]
	before_filter :get_box, only: [:index]
	before_filter :get_conversation, except: [:index, :empty_trash]

	def index
		@conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
		@inbox = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
		@trash = @mailbox.trash.paginate(page: params[:page], per_page: 10)
		@sent = @mailbox.sentbox.paginate(page: params[:page], per_page: 10)
	end

	def show 

	end

	def reply
		current_user.reply_to_conversation(@conversation, params[:body])
		flash[:success] = "Reply sent!"
		redirect_to conversation_path(@conversation)
	end

	def destroy 
		@conversation.move_to_trash(current_user)
		flash[:success] = "#{@conversation.subject} was moved to trash"
		redirect_to conversations_path
	end

	def restore
		@conversation.untrash(current_user)
		flash[:success] = "#{@conversation.subject} was restored"
		redirect_to conversations_path
	end

	def empty_trash
		@mailbox.trash.each do |conversation|
			conversation.receipts_for(current_user).update_all(deleted: true)
		end
		flash[:success] = 'Your trash was cleaned!'
		redirect_to conversations_path
	end

	def mark_as_read
		@conversation.mark_as_read(current_user)
		flash[:success] = "#{@conversation.subject} marked as read"
		redirect_to conversation_path
	end

	private 

	def get_mailbox
		@mailbox ||= current_user.mailbox
	end

	def get_conversation 
		@conversation ||= @mailbox.conversations.find(params[:id])
	end

	#this is designed to fetch the requested folder.
	def get_box
		if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
			params[:box] = 'inbox'
		end
		@box = params[:box]
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_filter :authenticate_user!

	def new
	end

	def create
	    recipients = User.where(id: params['recipients'])
	    conversation = current_user.send_message(recipients, params[:message][:body], 
	    				params[:message][:subject]).conversation
	    flash[:success] = "Message has been sent!"
	    redirect_to conversation_path(conversation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_header(text)
		content_for(:page_header) { text.to_s }
	end

	def gravatar_for(user, size=30, title=user.name)
		image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def mailbox_section(title, current_box, opts = {})
		opts[:class] = opts.fetch(:class, '')
		opts[:class] += ' active' if title.downcase == current_box
		content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def recipients_options
		s = ''
		User.all.each do |user|
			s << "<option value='#{user.id}'>#{user.name}</option>"
		end
		s.html_safe
	end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
	<%= link_to conversation.subject, conversation_path(conversation) %>

	<div class="btn-group-vertical pull-right">
	    <% if conversation.is_trashed?(current_user) %>
	        <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
	    <% else %>
	    	<%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
	                  data: {confirm: 'Are you sure?'} %>

	        <% if conversation.is_unread?(current_user) %>
	        	<%= link_to 'Mark as read', mark_as_read_conversation_path(conversation), 
	        			class: 'btn btn-xs btn-info', method: :post %>
	        <% end %>
	    <% end %>
	</div>

	<p><%= render 'conversations/participants', conversation: conversation %></p>
	 
    <p><%= conversation.last_message.body %>
      <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header "Your Conversations" %>

<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

<% page_header "Your Conversations" %>
 
<!-- tab things, they're awesome -->
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <!-- this working part isn't in the tutorial -->
  <div class="col-sm-9">
  	<% if @box == 'trash' %>
    	<p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p>

    	<ul class="list-group">
    		<%= render partial: 'conversations/conversation', collection: @trash %>
 		</ul>
  	<% elsif @box == 'inbox' %>

	  	<ul class="list-group">
	    	<%= render partial: 'conversations/conversation', collection: @inbox %>
	 	</ul>
	 <% elsif @box == 'sent' %>
	 	<ul class="list-group">
	    	<%= render partial: 'conversations/conversation', collection: @sent %>
	 	</ul>
	 <% end %>
 
  	<%= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>
 
<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
  <% @conversation.mark_as_read(current_user) %>
</p>
 
<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>
 
  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= gravatar_for message.sender, 45, message.sender.name %>
          </div>
 
          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
    </div>
    <%= submit_tag "Send Message", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synergy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>">
			<%= value %>
		</div>
	<% end %>

	<div class="page-header">
		<h1><%= yield :page_header%></h1>
	</div>

	<%= yield %>
  </div>
</head>
	<body>
		<nav class="navbar navbar-inverse">
		    <div class="container">
		      <div class="navbar-header">
		        <%= link_to 'Synergy', root_path, class: 'navbar-brand' %>
		      </div>

		      <ul class="nav navbar-nav">
		        <% if user_signed_in? %>
		          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
		          <li><%= link_to 'Your Conversations', conversations_path %></li>
		          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
		        <% else %>
		          <li><%= link_to 'Log In', new_user_session_path %></li>
		        <% end %>
		      </ul>
		      
		    </div>
		</nav>
	</body>
</html>

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>
 
<%= form_tag messages_path, method: :post do %>
	<div class = "form-group">
		<%= label_tag 'recipients', 'Choose recipients' %>
		<%= select_tag 'recipients', recipients_options, multiple: true, 
												class: 'form-control chosen-it' %>
	</div>

	<div class="form-group">
		<%= label_tag 'message[subject]', 'Subject' %>
		<%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
	</div>
	 
	<div class="form-group">
		<%= label_tag 'message[body]', 'Message' %>
		<%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
	</div>
	 
	<%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>